# -*- mode: ruby -*-
# vi: set ft=ruby :
# inspired from https://gist.github.com/dlutzy/2469037

boxes = [
  { 
    :name => :gobgp, 
    ip: '192.168.33.10', 
    :shell => 'bootstrap.sh'
  },
  { 
    :name => :quasar, 
    ip: '192.168.33.11', 
    :shell => 'bootstrap.sh',
    :sync_folder_local => '../',
    :sync_folder_remote => '/home/vagrant/go/src/github.com/amine7536/quasar',
  },
]

CUSTOM_CONFIG = {
  "BOX_NAME"  =>  "boxcutter/centos73",
}

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "512"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.provision :hostmanager

  boxes.each do |opts|
    config.vm.define opts[:name] do |boxconfig|
      boxconfig.vm.box        = CUSTOM_CONFIG['BOX_NAME']
      boxconfig.vm.hostname   = "%s.vagrant" % opts[:name].to_s
      boxconfig.vm.network      "private_network", ip: opts[:ip]
      boxconfig.hostmanager.aliases = opts[:name].to_s

      if opts[:shell]
        boxconfig.vm.provision :shell, path: opts[:shell].to_s, privileged: false
      end

      if (opts[:sync_folder_local] && opts[:sync_folder_remote])
        boxconfig.vm.synced_folder opts[:sync_folder_local].to_s, opts[:sync_folder_remote].to_s
      end
      
    end
  end

end