# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['LC_ALL'] = 'en_US.UTF-8'
GITUSER=`git config user.name`
GITUSEREMAIL=`git config user.email`

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  #
  # Build Server1
  #
  config.vm.define "golang" do |golang|

    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "2048"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
    end

    golang.vm.box = "boxcutter/centos73"
    golang.vm.box_url = "file:///Users/amine/Develop/github/boxcutter-centos/box/virtualbox/centos73-2.0.22.box"

    golang.vm.hostname = "buildvm.centos73-2.golang.lab"
    golang.vm.network :private_network, ip: "10.2.2.2"
    golang.hostmanager.aliases = %w(golang)

    golang.vm.synced_folder "../", "/home/vagrant/go/src/github.com/amine7536/quasar"

    golang.vm.provision "shell", inline: <<-SHELL
      sudo systemctl restart network
      sudo yum -y install epel-release
      sudo yum -y group install "Development Tools"
      # Set Git User/Email
      git config --global user.name \"#{GITUSER}\"
      git config --global user.name \"#{GITUSEREMAIL}\"
      # Golang
      wget -q https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz
      sudo tar -C /usr/local -xzf go1.8.1.linux-amd64.tar.gz
      # Set Golang env vars
      sed -ie '\$aexport GOPATH=\/home\/vagrant\/go' /home/vagrant/.bashrc
      sed -ie '\$aexport PATH=\$PATH:\/usr\/local\/go\/bin' /home/vagrant/.bashrc
      sed -ie '\$aexport PATH=\$PATH:\$GOPATH\/bin' /home/vagrant/.bashrc
      source /home/vagrant/.bashrc
      # Make Golang dir structure
      sudo mkdir /home/vagrant/go/bin
      sudo mkdir /home/vagrant/go/pkg
      sudo chown -R vagrant:vagrant /home/vagrant/go
      # Glide
      wget -q https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
      tar -C /home/vagrant/go/bin/ -xvf glide-v0.12.3-linux-amd64.tar.gz
      sudo mv /home/vagrant/go/bin/linux-amd64/glide /home/vagrant/go/bin/.
      # run build script, makefile ...

    SHELL

  end

end
